### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Rahix** [Rahix/shared-bus#14]
The current version is still pretty much what I drafted up initially.  The design has shown a few flaws over time, which should be addressed in a new version.  Here is an overview:

- [ ] The SPI proxy is **unsound** when shared across multiple tasks.  This is because the CS pin is handled outside the proxy.  Ref. #8 
- [ ] More existing mutexes should be supported out of the box.  E.g. anything implementing `lock-api`.  Ref. #9 
- [ ] If I'm not mistaken, sharing in a single execution context (`!Send`) can be done with even less overhead than the current `NullMutex`.  This should be explored.
- [ ] A macro should be added for pushing the bus-manager into a `static mut`, thus giving the references a `&'static` lifetime which makes sharing between tasks much easier. Ref. #13

**Comment by romancardenas** [comment]
Hi! First, thank you very much for your work, this crate looks great and makes sharing an interface very easy. I wonder how the support for RISC-V is. The [ESP Rust board](https://github.com/esp-rs/esp-rust-board-bsp) is a RISC-V microcontroller but is able to use this crate under the tensa feature.

Also, I saw a few of nice PRs for AVR microcontrollers and for a more uniform interface in this crate. How do you plan to add these features? May I help? I'm pretty new in the embedded Rust world, but I'd like to start contributing in useful projects.
